name: Build and deploy to Cloudflare

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Generate files
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build web
        run: flutter build web

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: build/web

      # - name: Deploy to Cloudflare Pages
      #   uses: cloudflare/wrangler-action@1.2.0
      #   with:
      #     apiToken: ${{ secrets.CF_API_TOKEN }}
      #     script: "wrangler publish"
