name: Build and deploy to Cloudflare

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          chche: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web

      # - name: Deploy to Cloudflare Pages
      #   uses: cloudflare/wrangler-action@1.2.0
      #   with:
      #     apiToken: ${{ secrets.CF_API_TOKEN }}
      #     script: "wrangler publish"
